### ISSUE TITLE
zplugで導入した場合にtms.plugin.zshが読み込めない

### ISSUE THREAD

**Issue by kadoyau** [yuki-ycino/tms#1]
表題の通りです。
Work aroundとしてtms側のコード修正をする方法でひとまず回避できましたので作業メモを添付いたします。
適切なPull Requestまで至らず申し訳ないです 🙇 
https://scrapbox.io/kadoyau/zplug%E3%81%A7tms%E3%82%92%E4%BD%BF%E3%81%8A%E3%81%86%E3%81%A8%E3%81%97%E3%81%9F%E3%82%89%E5%AE%9F%E8%A1%8C%E3%83%91%E3%82%B9%E3%82%92%E5%A4%89%E6%9B%B4%E3%81%99%E3%82%8B%E5%BF%85%E8%A6%81%E3%81%8C%E3%81%82%E3%81%A3%E3%81%9F

**Comment by yuki-yano** [comment]
Issueを見逃してしまっていました。今更の返答になってしまって申し訳ありません・・・

問題については理解しました。
が、これはzplug側の実装の都合だと思うので難しいですね・・・

例えば zplugin では

```
zplugin ice lucid wait"0" depth"1" as"program" src"tms.plugin.zsh" pick"tms"
zplugin light yuki-ycino/tms
```

とsrcの部分に読み込みたいファイルを書いておくことで事前にスクリプトを評価した上でPATHの通った場所にtmsを配置する、といったことができるので問題が起きていないのですが、類似の機能がないのであれば回避は難しそうに感じます。
（zplugは内部で複雑な動作をしていてこの辺りの解決はなかなか難しい印象を持っています。）

そもそも tms がzshプラグインの流儀に反しているのであれば修正しようかと思うのですが、そのあたりの知見はあったりするでしょうか。自分は適当に他のプラグインを参考にしつつ動くコードを書いてみた、というレベルなのでそもそもの設計がおかしいのかもしれません。

**Comment by kadoyau** [comment]
返信ありがとうございます！そして、zplugの内部実装に詳しいわけではなく知見がないです。すみません。
状況は理解することができましたし、もしzplugの方で知見がたまったら追記いたしますが、issueはcloseしてもよいかもしれませんね。

**Comment by yuki-yano** [comment]
了解しました。
Issueは一旦closeさせていただきます。
READMEのzplugの記述は削除しておいた方がよさそうですね。

**Comment by yuki-yano** [comment]
Fix: b19846c
